package kalafior;

import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class Gra extends javax.swing.JFrame {
String gracz ="O";
int licz=0;
int i,j;
String[][] tablica = new String[4][4];
public void spr_wynik(){
    if (tablica[1][1] == "X" && tablica[1][2] == "X" && tablica[1][3] == "X") { JOptionPane.showMessageDialog(null,"Wygrywa X"); reset(); }
            else if (tablica[2][1] == "X" && tablica[2][2] == "X" && tablica[2][3] == "X") { JOptionPane.showMessageDialog(null,"Wygrywa X"); reset(); }
            else if (tablica[3][1] == "X" && tablica[3][2] == "X" && tablica[3][3] == "X") { JOptionPane.showMessageDialog(null,"Wygrywa X"); reset(); }
            else if (tablica[1][1] == "X" && tablica[2][1] == "X" && tablica[3][1] == "X") { JOptionPane.showMessageDialog(null,"Wygrywa X"); reset(); }
            else if (tablica[1][2] == "X" && tablica[2][2] == "X" && tablica[3][2] == "X") { JOptionPane.showMessageDialog(null,"Wygrywa X"); reset(); }
            else if (tablica[1][3] == "X" && tablica[2][3] == "X" && tablica[3][3] == "X") { JOptionPane.showMessageDialog(null,"Wygrywa X"); reset(); }
            else if (tablica[1][1] == "X" && tablica[2][2] == "X" && tablica[3][3] == "X") { JOptionPane.showMessageDialog(null,"Wygrywa X"); reset(); }
            else if (tablica[1][3] == "X" && tablica[2][2] == "X" && tablica[3][1] == "X") { JOptionPane.showMessageDialog(null,"Wygrywa X"); reset(); }
            else { };

            if (tablica[1][1] == "O" && tablica[1][2] == "O" && tablica[1][3] == "O") { JOptionPane.showMessageDialog(null,"Wygrywa O"); reset(); }
            else if (tablica[2][1] == "O" && tablica[2][2] == "O" && tablica[2][3] == "O") { JOptionPane.showMessageDialog(null,"Wygrywa O"); reset(); }
            else if (tablica[3][1] == "O" && tablica[3][2] == "O" && tablica[3][3] == "O") { JOptionPane.showMessageDialog(null,"Wygrywa O"); reset(); }
            else if (tablica[1][1] == "O" && tablica[2][1] == "O" && tablica[3][1] == "O") { JOptionPane.showMessageDialog(null,"Wygrywa O"); reset(); }
            else if (tablica[1][2] == "O" && tablica[2][2] == "O" && tablica[3][2] == "O") { JOptionPane.showMessageDialog(null,"Wygrywa O"); reset(); }
            else if (tablica[1][3] == "O" && tablica[2][3] == "O" && tablica[3][3] == "O") { JOptionPane.showMessageDialog(null,"Wygrywa O"); reset(); }
            else if (tablica[1][1] == "O" && tablica[2][2] == "O" && tablica[3][3] == "O") { JOptionPane.showMessageDialog(null,"Wygrywa O"); reset(); }
            else if (tablica[1][3] == "O" && tablica[2][2] == "O" && tablica[3][1] == "O") { JOptionPane.showMessageDialog(null,"Wygrywa O"); reset(); }
            else { };

            if (licz==9) { JOptionPane.showMessageDialog(null,"Remis!"); reset(); }
    
}
 public void reset()
        {
            for(i=1;i<4;i++){
                for(j=1; j<4; j++) tablica[i][j] = "";
            }
            licz = 0;
            jButton1.setText("");
            jButton1.setEnabled(true);
            jButton2.setText("");
            jButton2.setEnabled(true);
            jButton3.setText("");
            jButton3.setEnabled(true);
            jButton4.setText("");
            jButton4.setEnabled(true);
            jButton5.setText("");
            jButton5.setEnabled(true);
            jButton6.setText("");
            jButton6.setEnabled(true);
            jButton7.setText("");
            jButton7.setEnabled(true);
            jButton8.setText("");
            jButton8.setEnabled(true);
            jButton9.setText("");
            jButton9.setEnabled(true);
            
            

            gracz = "O";
        }
    /**
     * Creates new form Gra
     */
    public Gra() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });

        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
        setVisible(true);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        jButton1.setLabel(gracz);
        tablica[1][1]=gracz;
        if (gracz == "O") gracz = "X";
        else gracz = "O";
        jButton1.setEnabled(false);
        licz++;
        spr_wynik();
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
    jButton2.setLabel(gracz);
        tablica[1][2]=gracz;
        if (gracz == "O") gracz = "X";
        else gracz = "O";
        jButton2.setEnabled(false);
        licz++;   
        spr_wynik();// TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
    jButton3.setLabel(gracz);
        tablica[1][3]=gracz;
        if (gracz == "O") gracz = "X";
        else gracz = "O";
        jButton3.setEnabled(false);
        licz++;   
        spr_wynik();// TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        jButton4.setLabel(gracz);
        tablica[2][1]=gracz;
        if (gracz == "O") gracz = "X";
        else gracz = "O";
        jButton4.setEnabled(false);
        licz++;   
        spr_wynik();// TODO add your handling code here:
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
    jButton5.setLabel(gracz);
        tablica[2][2]=gracz;
        if (gracz == "O") gracz = "X";
        else gracz = "O";
        jButton5.setEnabled(false);
        licz++;   
        spr_wynik();// TODO add your handling code here:
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
jButton6.setLabel(gracz);
        tablica[2][3]=gracz;
        if (gracz == "O") gracz = "X";
        else gracz = "O";
        jButton6.setEnabled(false);
        licz++;  
        spr_wynik();// TODO add your handling code here:
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
jButton7.setLabel(gracz);
        tablica[3][1]=gracz;
        if (gracz == "O") gracz = "X";
        else gracz = "O";
        jButton7.setEnabled(false);
        licz++; 
        spr_wynik();// TODO add your handling code here:
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
jButton8.setLabel(gracz);
        tablica[3][2]=gracz;
        if (gracz == "O") gracz = "X";
        else gracz = "O";
        jButton8.setEnabled(false);
        licz++; 
        spr_wynik();// TODO add your handling code here:
    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
jButton9.setLabel(gracz);
        tablica[3][3]=gracz;
        if (gracz == "O") gracz = "X";
        else gracz = "O";
        jButton9.setEnabled(false);
        licz++; 
        spr_wynik();// TODO add your handling code here:
    }//GEN-LAST:event_jButton9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    // End of variables declaration//GEN-END:variables
}
